### ISSUE TITLE
Creating a history sharing link often fails

### ISSUE THREAD

**Issue by hechth** [CESNET/usegalaxy#23]
If I try to create the sharing URL for a history, the process takes a long time and often times out, not creating a link to share.

**Comment by martindemko** [comment]
Hi, I just tried and the link was created successfully. Maybe I used a different way. How did you approach to it? Coul you add a screenshot with the error state, please?

**Comment by hechth** [comment]
It does work sometimes but sometimes it also just doesn't happen and after 2 minutes or so it shows an error message.

**Comment by hechth** [comment]
The histories have 10k+ datasets - maybe that is the reason? Also they contain 150+ GB of data.

**Comment by zsalvet** [comment]
That could be part of the reason, publishing a history means publishing each of its datasets and the latter operation involves database write...

**Comment by martindemko** [comment]
I raised the Nginx proxy_read_timeout and send_toimeout timeouts (to 600s) as this might need more time to be processed, obviously. Could you retry, please?

**Comment by hechth** [comment]
Yep, that worked quite smoothly now, but also on a bit smaller history - but anyways!

**Comment by hechth** [comment]
Tested it on one more larger history and seems to work fine now - thanks!

**Comment by martindemko** [comment]
Glad to hear that
