### ISSUE TITLE
Adding tools from the test toolshed

### ISSUE THREAD

**Issue by hechth** [CESNET/usegalaxy#24]
Is it possible to install tools from the test toolshed using the same `umsa_tools.yaml` file as the tools from the normal toolshed? Or would this have to be done differently?

**Comment by martindemko** [comment]
Hi, I was told that the test toolshed is no longer meant to provide tools for Galaxy instances. It should be used for the development of tools in the local environment using Planemo, I think. AFAIK there is no simple way to install tools from testtoolshed into Galaxy instance.
