### ISSUE TITLE
Update UMSA tool list

### ISSUE THREAD

**Issue by hechth** [CESNET/usegalaxy#8]
Add all tools to be installed on UMSA tool list.

**Comment by martindemko** [comment]
done

**Comment by hechth** [comment]
@martindemko could you please make changes with pull requests and then ping me as a reviwer? Otherwise this is too chaotic - thanks!

**Comment by martindemko** [comment]
Sorry, I remember that I did some update in tool_list last week or so, and I thought it was this one.

**Comment by hechth** [comment]
The newest revisions of all tools needed for processing need to be added to this file: https://github.com/CESNET/usegalaxy/blob/galaxy-umsa/umsa_tool_list.yaml

**Comment by hechth** [comment]
@martindemko we for now have all tools we need AFAIK so with that I'm closing this. We will open new issues for individual tools from then on :)
